site_name: HajjGuide Thesis for Hasan.VC Venture Studio
site_description: Business read-only one-pager
# site_url: https://<your-username>.github.io/<your-repo>/
# repo_url: https://github.com/<your-username>/<your-repo>

nav:
  - Thesis: index.md
  - Competitive Landscape:
    - Detailed Competitor Table:  https://docs.google.com/spreadsheets/d/1rgbg8PFvxG_L-yodOR_RfjXNCsfgLvZ8ZjEdNqVgNlg
    - Competitor Rubic: https://docs.google.com/spreadsheets/d/1rgbg8PFvxG_L-yodOR_RfjXNCsfgLvZ8ZjEdNqVgNlg/edit?gid=1266947592#gid=1266947592
  - Interview Glossary:
    - Interview Glossary: https://drive.google.com/drive/folders/1Nl2WR8vFc7RmS8BeiXq9PS4L2vOr__OX
    - Initial Hypothesis (H0): https://docs.google.com/spreadsheets/d/1l0BbO2Bb7xJzLw5z6cI2tvYLts68JkFvqWlkoBQ6SXM
    - Pilgrim Questions Bank: https://docs.google.com/spreadsheets/d/12dxCk7lgH-1IsgSj3lxy94h0zS79Jhf86fr3RsK4Rtg
    - Agency Questions Bank: https://docs.google.com/spreadsheets/d/1Z2YS4TTYi7ElV4fs34Isic8189Y_TOABN7g0mwsW_zc
    - Meeting Notes Index: https://docs.google.com/spreadsheets/d/1PMjvoq412shnjJoWM3RJM05qVJhKSduIdGKXV0Dgjac
    - Raw Media Index: https://docs.google.com/spreadsheets/d/1PKmJoPh4QfTytIR_lzH2bpdG74Cd7YwijRzqeNQG468
  - Meeting Notes and Transcripts: interviews/index.md
  - Full TAM Calculation: tam_calculation.md
  - Prototype:
    - Agency B2B2C Marketplace: https://hajjya-remake.vercel.app/
    - iOS App (iphone, ipad only): https://apps.apple.com/ca/app/qaniteen/id6746473610
    - Android App: https://play.google.com/store/apps/details?id=com.mycompany.qaniteen&hl=en

theme:
  name: material
  logo: assets/logo.png
  palette:
    # Light mode (default)
    - scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode (optional toggle)
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/fonts.css
